### ISSUE TITLE
Fastly::Error gives no useable information

### ISSUE THREAD

**Issue by yob** [fastly/fastly-ruby#34]
While exploring the fastly API, I was getting a `Fastly::Error` with a message of "Bad Request". Here's some sample output from my script:

``` bash
⚡ ruby fastly-test.rb
/home/jh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastly-1.1.3/lib/fastly/client.rb:90:in `post_and_put': Bad Request (Fastly::Error)
        from /home/jh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastly-1.1.3/lib/fastly/client.rb:77:in `put'
        from /home/jh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastly-1.1.3/lib/fastly/fetcher.rb:42:in `update'
        from /home/jh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastly-1.1.3/lib/fastly.rb:175:in `block (2 levels) in <class:Fastly>'
        from failover.rb:15:in `<main>'
```

Being unfamiliar with the API, it was impossible to debug what I was doing wrong.

I added some debuging to the fastly gem, and then output of my script became:

``` bash
⚡ ruby fastly-test.rb
{"msg":"An error occurred while connecting to the fastly API, please try your request again.","detail":"Version '4' for service 'XXXXXXX' is locked"}
/home/jh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastly-1.1.3/lib/fastly/client.rb:90:in `post_and_put': Bad Request (Fastly::Error)
        from /home/jh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastly-1.1.3/lib/fastly/client.rb:77:in `put'
        from /home/jh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastly-1.1.3/lib/fastly/fetcher.rb:42:in `update'
        from /home/jh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastly-1.1.3/lib/fastly.rb:175:in `block (2 levels) in <class:Fastly>'
        from failover.rb:15:in `<main>'
```

It would be super helpful if the error message in the body of the response was added to the Fastly::Error object to make it easier to see what's going on.

**Comment by Integralist** [comment]
Closing this issue now we've published v4.0.0 https://rubygems.org/gems/fastly
